window.MOVIES = [
  {"id":1,"p":"Apple TV","t":"글래디에이터","e":"Gladiator","y":2000,"m":154,"g":"액션/드라마","d":"리들리 스콧","s":"글래디에이터"},
  {"id":2,"p":"Apple TV","t":"다크 나이트","e":"The Dark Knight","y":2008,"m":152,"g":"액션/범죄","d":"크리스토퍼 놀란","s":"다크나이트 3부작"},
  {"id":3,"p":"Apple TV","t":"다크 나이트 라이즈","e":"The Dark Knight Rises","y":2012,"m":164,"g":"액션/범죄","d":"크리스토퍼 놀란","s":"다크나이트 3부작"},
  {"id":4,"p":"Apple TV","t":"던커크","e":"Dunkirk","y":2017,"m":106,"g":"전쟁/드라마","d":"크리스토퍼 놀란","s":"-"},
  {"id":5,"p":"Apple TV","t":"듄","e":"Dune","y":2021,"m":155,"g":"SF/드라마","d":"드니 빌뇌브","s":"듄"},
  {"id":6,"p":"Apple TV","t":"듄: 파트 2","e":"Dune: Part Two","y":2024,"m":165,"g":"SF/드라마","d":"드니 빌뇌브","s":"듄"},
  {"id":7,"p":"Apple TV","t":"디파티드","e":"The Departed","y":2006,"m":151,"g":"범죄/스릴러","d":"마틴 스코세이지","s":"-"},
  {"id":8,"p":"Apple TV","t":"멀홀랜드 드라이브","e":"Mulholland Drive","y":2001,"m":147,"g":"미스터리","d":"데이비드 린치","s":"-"},
  {"id":9,"p":"Apple TV","t":"메간","e":"M3GAN","y":2023,"m":101,"g":"SF/호러","d":"제라드 존스톤","s":"-"},
  {"id":10,"p":"Apple TV","t":"미션 임파서블","e":"Mission: Impossible","y":1996,"m":110,"g":"액션/스파이","d":"브라이언 드 팔마","s":"미션 임파서블"},
  {"id":11,"p":"Apple TV","t":"미션 임파서블 2","e":"Mission: Impossible II","y":2000,"m":123,"g":"액션/스파이","d":"오우삼","s":"미션 임파서블"},
  {"id":12,"p":"Apple TV","t":"미션 임파서블 3","e":"Mission: Impossible III","y":2006,"m":125,"g":"액션/스파이","d":"J.J. 에이브럼스","s":"미션 임파서블"},
  {"id":13,"p":"Apple TV","t":"미션 임파서블: 고스트 프로토콜","e":"Mission: Impossible - Ghost Protocol","y":2011,"m":132,"g":"액션/스파이","d":"브래드 버드","s":"미션 임파서블"},
  {"id":14,"p":"Apple TV","t":"미션 임파서블: 로그네이션","e":"Mission: Impossible - Rogue Nation","y":2015,"m":131,"g":"액션/스파이","d":"크리스토퍼 맥쿼리","s":"미션 임파서블"},
  {"id":15,"p":"Apple TV","t":"미션 임파서블: 폴아웃","e":"Mission: Impossible - Fallout","y":2018,"m":147,"g":"액션/스파이","d":"크리스토퍼 맥쿼리","s":"미션 임파서블"},
  {"id":16,"p":"Apple TV","t":"미션 임파서블: 데드 레코닝","e":"Mission: Impossible - Dead Reckoning Part One","y":2023,"m":163,"g":"액션/스파이","d":"크리스토퍼 맥쿼리","s":"미션 임파서블"},
  {"id":17,"p":"Apple TV","t":"미션 임파서블: 파이널 레코닝","e":"Mission: Impossible - The Final Reckoning","y":2025,"m":169,"g":"액션/스파이","d":"크리스토퍼 맥쿼리","s":"미션 임파서블"},
  {"id":18,"p":"Apple TV","t":"반지의 제왕: 반지 원정대 (확장판)","e":"The Lord of the Rings: The Fellowship of the Ring","y":2001,"m":208,"g":"판타지/모험","d":"피터 잭슨","s":"반지의 제왕"},
  {"id":19,"p":"Apple TV","t":"반지의 제왕: 두 개의 탑 (확장판)","e":"The Lord of the Rings: The Two Towers","y":2002,"m":223,"g":"판타지/모험","d":"피터 잭슨","s":"반지의 제왕"},
  {"id":20,"p":"Apple TV","t":"반지의 제왕: 왕의 귀환 (확장판)","e":"The Lord of the Rings: The Return of the King","y":2003,"m":200,"g":"판타지/모험","d":"피터 잭슨","s":"반지의 제왕"},
  {"id":21,"p":"Apple TV","t":"반지의 제왕: 로히림의 전쟁","e":"The Lord of the Rings: The War of the Rohirrim","y":2024,"m":134,"g":"애니/판타지","d":"카미야마 켄지","s":"반지의 제왕"},
  {"id":22,"p":"Apple TV","t":"배트맨 비긴즈","e":"Batman Begins","y":2005,"m":140,"g":"액션/범죄","d":"크리스토퍼 놀란","s":"다크나이트 3부작"},
  {"id":23,"p":"Apple TV","t":"버즈 라이트이어","e":"Lightyear","y":2022,"m":105,"g":"애니메이션","d":"앵거스 맥레인","s":"토이 스토리"},
  {"id":24,"p":"Apple TV","t":"블랙호크 다운","e":"Black Hawk Down","y":2001,"m":144,"g":"전쟁/액션","d":"리들리 스콧","s":"-"},
  {"id":25,"p":"Apple TV","t":"서울의 봄","e":"12.12: The Day","y":2023,"m":141,"g":"드라마/역사","d":"김성수","s":"-"},
  {"id":26,"p":"Apple TV","t":"슈퍼맨 (2025)","e":"Superman","y":2025,"m":143,"g":"히어로","d":"제임스 건","s":"DC"},
  {"id":27,"p":"Apple TV","t":"슈퍼맨 더 무비","e":"Superman","y":1978,"m":154,"g":"히어로","d":"리처드 도너","s":"DC"},
  {"id":28,"p":"Apple TV","t":"슈퍼맨 리턴즈","e":"Superman Returns","y":2006,"m":154,"g":"히어로","d":"브라이언 싱어","s":"DC"},
  {"id":29,"p":"Apple TV","t":"에이리언: 로물루스","e":"Alien: Romulus","y":2024,"m":119,"g":"SF/호러","d":"페데 알바레즈","s":"-"},
  {"id":30,"p":"Apple TV","t":"왕과 사는 남자","e":"The Man Who Lives with the King","y":2026,"m":117,"g":"사극/드라마","d":"장항준","s":"-"},
  {"id":31,"p":"Apple TV","t":"미녀스: 죄인들","e":"Sinners","y":2025,"m":118,"g":"호러/드라마","d":"라이언 쿠글러","s":"-"},
  {"id":32,"p":"Apple TV","t":"인셉션","e":"Inception","y":2010,"m":148,"g":"SF/액션","d":"크리스토퍼 놀란","s":"-"},
  {"id":33,"p":"Apple TV","t":"인터스텔라","e":"Interstellar","y":2014,"m":169,"g":"SF/드라마","d":"크리스토퍼 놀란","s":"-"},
  {"id":34,"p":"Apple TV","t":"저스티스 리그 (잭 스나이더 컷)","e":"Zack Snyder's Justice League","y":2021,"m":242,"g":"히어로","d":"잭 스나이더","s":"DC"},
  {"id":35,"p":"Apple TV","t":"챌린저스","e":"Challengers","y":2024,"m":131,"g":"드라마/스포츠","d":"루카 구아다니노","s":"-"},
  {"id":36,"p":"Apple TV","t":"콘크리트 유토피아","e":"Concrete Utopia","y":2023,"m":130,"g":"드라마/재난","d":"엄태화","s":"-"},
  {"id":37,"p":"Apple TV","t":"탑건: 매버릭","e":"Top Gun: Maverick","y":2022,"m":130,"g":"액션/드라마","d":"조셉 코신스키","s":"탑건"},
  {"id":38,"p":"Apple TV","t":"테넷","e":"Tenet","y":2020,"m":150,"g":"SF/액션","d":"크리스토퍼 놀란","s":"-"},
  {"id":39,"p":"Apple TV","t":"토이 스토리","e":"Toy Story","y":1995,"m":81,"g":"애니메이션","d":"존 라세터","s":"토이 스토리"},
  {"id":40,"p":"Apple TV","t":"토이 스토리 2","e":"Toy Story 2","y":1999,"m":92,"g":"애니메이션","d":"존 라세터","s":"토이 스토리"},
  {"id":41,"p":"Apple TV","t":"토이 스토리 3","e":"Toy Story 3","y":2010,"m":103,"g":"애니메이션","d":"리 언크리치","s":"토이 스토리"},
  {"id":42,"p":"Apple TV","t":"토이 스토리 4","e":"Toy Story 4","y":2019,"m":100,"g":"애니메이션","d":"조시 쿨리","s":"토이 스토리"},
  {"id":43,"p":"Apple TV","t":"파이널 데스티네이션: 블러드라인","e":"Final Destination Bloodlines","y":2025,"m":109,"g":"호러","d":"잭 알렉산더","s":"-"},
  {"id":44,"p":"Apple TV","t":"프로젝트 헤일메리","e":"Project Hail Mary","y":2025,"m":156,"g":"SF/모험","d":"필 로드","s":"-"},
  {"id":45,"p":"Apple TV","t":"F1 더 무비","e":"F1","y":2025,"m":155,"g":"액션/드라마","d":"조셉 코신스키","s":"-"},
  {"id":46,"p":"Google TV","t":"에브리씽 에브리웨어 올 앳 원스","e":"Everything Everywhere All at Once","y":2022,"m":139,"g":"SF/코미디","d":"다니엘 관","s":"-"},
  {"id":47,"p":"Google TV","t":"더 울프 오브 월스트리트","e":"The Wolf of Wall Street","y":2013,"m":179,"g":"범죄/전기","d":"마틴 스코세이지","s":"-"},
  {"id":48,"p":"Google TV","t":"더 배트맨","e":"The Batman","y":2022,"m":176,"g":"히어로/범죄","d":"맷 리브스","s":"DC"},
  {"id":49,"p":"Google TV","t":"스파이더맨","e":"Spider-Man","y":2002,"m":121,"g":"히어로","d":"샘 레이미","s":"스파이더맨 (레이미)"},
  {"id":50,"p":"Google TV","t":"스파이더맨 2","e":"Spider-Man 2","y":2004,"m":127,"g":"히어로","d":"샘 레이미","s":"스파이더맨 (레이미)"},
  {"id":51,"p":"Google TV","t":"스파이더맨: 홈커밍","e":"Spider-Man: Homecoming","y":2017,"m":133,"g":"히어로","d":"존 왓츠","s":"스파이더맨 (MCU)"},
  {"id":52,"p":"Google TV","t":"스파이더맨: 파 프롬 홈","e":"Spider-Man: Far From Home","y":2019,"m":129,"g":"히어로","d":"존 왓츠","s":"스파이더맨 (MCU)"},
  {"id":53,"p":"Google TV","t":"스파이더맨: 노 웨이 홈","e":"Spider-Man: No Way Home","y":2021,"m":148,"g":"히어로","d":"존 왓츠","s":"스파이더맨 (MCU)"},
  {"id":54,"p":"Google TV","t":"스파이더맨: 뉴 유니버스","e":"Spider-Man: Into the Spider-Verse","y":2018,"m":117,"g":"애니/히어로","d":"밥 퍼시게티","s":"스파이더버스"},
  {"id":55,"p":"Google TV","t":"어메이징 스파이더맨","e":"The Amazing Spider-Man","y":2012,"m":136,"g":"히어로","d":"마크 웹","s":"어메이징 스파이더맨"},
  {"id":56,"p":"Google TV","t":"어메이징 스파이더맨 2","e":"The Amazing Spider-Man 2","y":2014,"m":142,"g":"히어로","d":"마크 웹","s":"어메이징 스파이더맨"},
  {"id":57,"p":"Google TV","t":"영웅본색","e":"A Better Tomorrow","y":1987,"m":96,"g":"액션/느와르","d":"오우삼","s":"-"},
  {"id":58,"p":"Google TV","t":"기생충 (흑백판)","e":"Parasite","y":2019,"m":131,"g":"스릴러/드라마","d":"봉준호","s":"-"},
  {"id":59,"p":"Google TV","t":"존 윅","e":"John Wick","y":2014,"m":101,"g":"액션/스릴러","d":"채드 스타헬스키","s":"존 윅"},
  {"id":60,"p":"Google TV","t":"존 윅: 리로드","e":"John Wick: Chapter 2","y":2017,"m":122,"g":"액션/스릴러","d":"채드 스타헬스키","s":"존 윅"},
  {"id":61,"p":"Google TV","t":"허트 로커","e":"The Hurt Locker","y":2008,"m":131,"g":"전쟁/드라마","d":"캐서린 비글로우","s":"-"},
  {"id":62,"p":"Google TV","t":"아이언맨","e":"Iron Man","y":2008,"m":126,"g":"히어로/SF","d":"존 파브로","s":"MCU"},
  {"id":63,"p":"Google TV","t":"어벤져스: 인피니티 워","e":"Avengers: Infinity War","y":2018,"m":149,"g":"히어로","d":"루소 형제","s":"MCU"},
  {"id":64,"p":"Google TV","t":"어벤져스: 엔드게임","e":"Avengers: Endgame","y":2019,"m":181,"g":"히어로","d":"루소 형제","s":"MCU"},
  {"id":65,"p":"Google TV","t":"캡틴 아메리카: 시빌 워","e":"Captain America: Civil War","y":2016,"m":148,"g":"히어로","d":"루소 형제","s":"MCU"},
  {"id":66,"p":"Google TV","t":"토르: 라그나로크","e":"Thor: Ragnarok","y":2017,"m":130,"g":"히어로/코미디","d":"타이카 와이티티","s":"MCU"},
  {"id":67,"p":"Google TV","t":"극한직업","e":"Extreme Job","y":2019,"m":111,"g":"코미디/범죄","d":"이병헌(감독)","s":"-"},
  {"id":68,"p":"Google TV","t":"범죄도시","e":"The Outlaws","y":2017,"m":121,"g":"범죄/액션","d":"강윤성","s":"-"},
  {"id":69,"p":"Google TV","t":"마스터","e":"Master","y":2016,"m":143,"g":"범죄/드라마","d":"조의석","s":"-"},
  {"id":70,"p":"Google TV","t":"신세계","e":"New World","y":2013,"m":135,"g":"범죄/드라마","d":"박훈정","s":"-"},
  {"id":71,"p":"Google TV","t":"악마를 보았다","e":"I Saw the Devil","y":2010,"m":144,"g":"스릴러/범죄","d":"김지운","s":"-"},
  {"id":72,"p":"Google TV","t":"황해 (감독판)","e":"The Yellow Sea","y":2010,"m":157,"g":"범죄/스릴러","d":"나홍진","s":"-"},
  {"id":73,"p":"Google TV","t":"아가씨","e":"The Handmaiden","y":2016,"m":151,"g":"스릴러/드라마","d":"박찬욱","s":"-"},
  {"id":74,"p":"Google TV","t":"부산행","e":"Train to Busan","y":2016,"m":118,"g":"호러/액션","d":"연상호","s":"-"},
  {"id":75,"p":"Google TV","t":"변호인","e":"The Attorney","y":2013,"m":127,"g":"드라마/법정","d":"양우석","s":"-"},
  {"id":76,"p":"Google TV","t":"건축학개론","e":"Architecture 101","y":2012,"m":116,"g":"드라마/로맨스","d":"이용주","s":"-"},
  {"id":77,"p":"Google TV","t":"중경삼림","e":"Chungking Express","y":1994,"m":97,"g":"드라마/로맨스","d":"왕가위","s":"-"},
  {"id":78,"p":"Google TV","t":"백 투 더 퓨처","e":"Back to the Future","y":1985,"m":117,"g":"SF/코미디","d":"로버트 저메키스","s":"백 투 더 퓨처"},
  {"id":79,"p":"Google TV","t":"백 투 더 퓨처 2","e":"Back to the Future Part II","y":1989,"m":108,"g":"SF/코미디","d":"로버트 저메키스","s":"백 투 더 퓨처"},
  {"id":80,"p":"Google TV","t":"백 투 더 퓨처 3","e":"Back to the Future Part III","y":1990,"m":119,"g":"SF/코미디","d":"로버트 저메키스","s":"백 투 더 퓨처"},
  {"id":81,"p":"Google TV","t":"위플래쉬","e":"Whiplash","y":2014,"m":107,"g":"드라마/음악","d":"데이미언 셔젤","s":"-"},
  {"id":82,"p":"Google TV","t":"빅쇼트","e":"The Big Short","y":2015,"m":130,"g":"드라마/전기","d":"아담 맥케이","s":"-"},
  {"id":83,"p":"Google TV","t":"달라스 바이어스 클럽","e":"Dallas Buyers Club","y":2013,"m":117,"g":"드라마/전기","d":"장마르크 발레","s":"-"},
  {"id":84,"p":"Google TV","t":"노예 12년","e":"12 Years a Slave","y":2013,"m":134,"g":"드라마/역사","d":"스티브 맥퀸","s":"-"},
  {"id":85,"p":"Google TV","t":"인생은 아름다워","e":"Life Is Beautiful","y":1997,"m":116,"g":"드라마/전쟁","d":"로베르토 베니니","s":"-"},
  {"id":86,"p":"Google TV","t":"시네마 천국","e":"Cinema Paradiso","y":1988,"m":155,"g":"드라마","d":"주세페 토르나토레","s":"-"},
  {"id":87,"p":"Google TV","t":"이터널 선샤인","e":"Eternal Sunshine of the Spotless Mind","y":2004,"m":108,"g":"SF/로맨스","d":"미셸 공드리","s":"-"},
  {"id":88,"p":"Google TV","t":"소스 코드","e":"Source Code","y":2011,"m":93,"g":"SF/스릴러","d":"던칸 존스","s":"-"},
  {"id":89,"p":"Google TV","t":"그을린 사랑","e":"Incendies","y":2010,"m":131,"g":"드라마/미스터리","d":"드니 빌뇌브","s":"-"},
  {"id":90,"p":"Google TV","t":"퍼펙트 블루","e":"Perfect Blue","y":1997,"m":81,"g":"애니/스릴러","d":"사토시 콘","s":"-"},
  {"id":91,"p":"Google TV","t":"해리 포터와 마법사의 돌","e":"Harry Potter and the Philosopher's Stone","y":2001,"m":152,"g":"판타지/모험","d":"크리스 콜럼버스","s":"해리 포터"},
  {"id":92,"p":"Google TV","t":"해리 포터와 비밀의 방","e":"Harry Potter and the Chamber of Secrets","y":2002,"m":161,"g":"판타지/모험","d":"크리스 콜럼버스","s":"해리 포터"},
  {"id":93,"p":"Google TV","t":"해리 포터와 아즈카반의 죄수","e":"Harry Potter and the Prisoner of Azkaban","y":2004,"m":142,"g":"판타지/모험","d":"알폰소 쿠아론","s":"해리 포터"},
  {"id":94,"p":"Google TV","t":"해리 포터와 불의 잔","e":"Harry Potter and the Goblet of Fire","y":2005,"m":157,"g":"판타지/모험","d":"마이크 뉴웰","s":"해리 포터"},
  {"id":95,"p":"Google TV","t":"해리포터와 불사조 기사단","e":"Harry Potter and the Order of the Phoenix","y":2007,"m":138,"g":"판타지/모험","d":"데이비드 예이츠","s":"해리 포터"},
  {"id":96,"p":"Google TV","t":"해리포터와 혼혈왕자","e":"Harry Potter and the Half-Blood Prince","y":2009,"m":153,"g":"판타지/모험","d":"데이비드 예이츠","s":"해리 포터"},
  {"id":97,"p":"Google TV","t":"해리포터와 죽음의 성물 1","e":"Harry Potter and the Deathly Hallows: Part 1","y":2010,"m":146,"g":"판타지/모험","d":"데이비드 예이츠","s":"해리 포터"},
  {"id":98,"p":"Google TV","t":"해리 포터와 죽음의 성물 2","e":"Harry Potter and the Deathly Hallows: Part 2","y":2011,"m":130,"g":"판타지/모험","d":"데이비드 예이츠","s":"해리 포터"},
  {"id":99,"p":"Google TV","t":"호빗: 뜻밖의 여정","e":"The Hobbit: An Unexpected Journey","y":2012,"m":169,"g":"판타지/모험","d":"피터 잭슨","s":"호빗"},
  {"id":100,"p":"Google TV","t":"호빗: 스마우그의 폐허","e":"The Hobbit: The Desolation of Smaug","y":2013,"m":161,"g":"판타지/모험","d":"피터 잭슨","s":"호빗"},
  {"id":101,"p":"Google TV","t":"호빗: 다섯 군대의 전투","e":"The Hobbit: The Battle of the Five Armies","y":2014,"m":144,"g":"판타지/모험","d":"피터 잭슨","s":"호빗"},
  {"id":102,"p":"Google TV","t":"무간도","e":"Infernal Affairs","y":2002,"m":101,"g":"범죄/스릴러","d":"유위강","s":"무간도"},
  {"id":103,"p":"Google TV","t":"무간도 2","e":"Infernal Affairs II","y":2003,"m":119,"g":"범죄/스릴러","d":"유위강","s":"무간도"},
  {"id":104,"p":"Google TV","t":"무간도 3","e":"Infernal Affairs III","y":2003,"m":118,"g":"범죄/스릴러","d":"유위강","s":"무간도"},
  {"id":105,"p":"Google TV","t":"배트맨 v 슈퍼맨","e":"Batman v Superman: Dawn of Justice","y":2016,"m":182,"g":"히어로","d":"잭 스나이더","s":"DC"},
  {"id":106,"p":"Google TV","t":"맨 오브 스틸","e":"Man of Steel","y":2013,"m":143,"g":"히어로","d":"잭 스나이더","s":"DC"},
  {"id":107,"p":"Google TV","t":"장화, 홍련","e":"A Tale of Two Sisters","y":2003,"m":115,"g":"호러/미스터리","d":"김지운","s":"-"},
  {"id":108,"p":"Google TV","t":"테이큰","e":"Taken","y":2008,"m":93,"g":"액션/스릴러","d":"피에르 모렐","s":"-"},
  {"id":109,"p":"Google TV","t":"엔더스 게임","e":"Ender's Game","y":2013,"m":114,"g":"SF/액션","d":"개빈 후드","s":"-"},
  {"id":110,"p":"Google TV","t":"타임 패러독스","e":"Predestination","y":2014,"m":97,"g":"SF/스릴러","d":"스피에릭 형제","s":"-"}
];
